#!/usr/bin/env python3
"""Render the timeline from data into timeline/index.html and evidence.html.

Why a generator rather than fetching JSON in the browser: this site has no
build step and has to stay useful with JavaScript off. Rendering client-side
would put the whole timeline behind JS, which is exactly the failure the page
is written against, and would hide it from the crawlers llms.txt exists to
serve. Rendering at author time keeps one structured source of truth
(data/timeline.json) and ships plain static HTML. Expand and collapse is
native <details>, so that works with no script either.

Three generated blocks live between markers and are committed, so the file on
disk is the file that is served:

  timeline/index.html   the entries
  index.html            the homepage entry point, including its counts
  evidence.html         the appendix of recorded runs (data/runs.json)

The homepage counts are generated rather than typed so a claim about the
timeline cannot drift away from the timeline. --check re-renders and compares,
which is what stops any of the three drifting apart.

Standard library only, so CI needs no install step.

    python3 tool/render-timeline.py           # write
    python3 tool/render-timeline.py --check   # verify committed HTML matches data
"""

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "timeline.json"
PAGE = ROOT / "timeline" / "index.html"
HOME = ROOT / "index.html"
RUNS = ROOT / "data" / "runs.json"
RUNS_PAGE = ROOT / "evidence.html"

START = "<!-- timeline:start · generated by tool/render-timeline.py · edit data/timeline.json -->"
END = "<!-- timeline:end -->"
HOME_START = "<!-- timeline-entry:start · generated by tool/render-timeline.py · edit data/timeline.json -->"
HOME_END = "<!-- timeline-entry:end -->"
RUNS_START = "<!-- runs:start · generated by tool/render-timeline.py · edit data/runs.json -->"
RUNS_END = "<!-- runs:end -->"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# The order a thought is read in: what I was doing, what I believed, what I
# saw, what I made of it, what it changed, where it landed. Only the fields an
# entry actually carries are rendered — an entry is not a form to complete.
FIELDS = [
    ("Context", "context"),
    ("Original thought", "thought"),
    ("Observation", "observation"),
    ("Mental model", "model"),
    ("What changed", "changed"),
    ("Application", "application"),
]

# REVISED and SUPERSEDED are the page's subject, so they carry a marker class.
# Everything else is quiet grey text at the size of the date: a reader should
# meet the thought before the label on it.
TURNED = {"REVISED", "SUPERSEDED"}


def e(text) -> str:
    return html.escape(str(text), quote=True)


def short_date(iso: str) -> str:
    y, m, d = iso.split("-")
    return f"{MONTHS[int(m) - 1]} {int(d)}"


def field(label: str, value: str, cls: str = "") -> str:
    c = f' class="{cls}"' if cls else ""
    return f"        <div><dt>{e(label)}</dt><dd{c}>{value}</dd></div>\n"


def evidence_list(items: list) -> str:
    out = []
    for it in items:
        label = e(it["label"])
        url = it.get("url")
        body = f'<a href="{e(url)}" rel="noreferrer">{label}</a>' if url else label
        repo = it.get("repo")
        if repo:
            tail = e(repo)
            access = it.get("access")
            if access == "private":
                tail += " · private repository, reference not a link"
            elif access == "local":
                tail += " · local repository, not published"
            body += f' <span class="quiet">{tail}</span>'
        out.append(f"<li>{body}</li>")
    return '<ul class="ev">' + "".join(out) + "</ul>"


def related_list(items: list, known: dict) -> str:
    """Links between entries are same-page anchors, so a revision chain is one
    click in either direction and still works with no script."""
    out = []
    for r in items:
        target = known.get(r["id"])
        if target is None:
            raise SystemExit(f"related id {r['id']!r} matches no entry")
        out.append(
            f'<li>{e(r["rel"])} <a href="#t-{e(r["id"])}">'
            f'{e(short_date(target["date"]))} · {e(target["title"])}</a></li>'
        )
    return '<ul class="ev">' + "".join(out) + "</ul>"


def render(data: dict) -> str:
    # Newest first. Python's sort is stable, so entries sharing a date keep
    # the order they have in the data file — which is where the sequence
    # within a single day is recorded, since a date cannot express it.
    entries = sorted(data["entries"], key=lambda x: x["date"], reverse=True)
    known = {x["id"]: x for x in data["entries"]}
    if len(known) != len(entries):
        raise SystemExit("two entries share an id")

    parts = []
    year = None
    for entry in entries:
        y = entry["date"][:4]
        if y != year:
            if year is not None:
                parts.append("      </div>\n")
            year = y
            parts.append(f'      <p class="logyear">{e(y)}</p>\n')
            parts.append('      <div class="log">\n')

        status = entry["status"]
        if status not in data["statuses"]:
            raise SystemExit(f"unknown status {status!r} on {entry['id']}")
        cls = "state state--turned" if status in TURNED else "state"

        parts.append(f'      <details class="entry" id="t-{e(entry["id"])}">\n')
        parts.append("        <summary>\n")
        parts.append(f'          <span class="when">{e(short_date(entry["date"]))}</span>\n')
        parts.append(f'          <span class="what">{e(entry["title"])}</span>\n')
        parts.append(f'          <span class="{cls}">{e(status)}</span>\n')
        parts.append("        </summary>\n")
        parts.append('        <div class="entrybody">\n')
        parts.append('          <dl class="find">\n')

        for label, key in FIELDS:
            if entry.get(key):
                parts.append(field(label, e(entry[key])))
        if entry.get("related"):
            parts.append(field("Related", related_list(entry["related"], known)))
        if entry.get("evidence"):
            parts.append(field("Evidence", evidence_list(entry["evidence"])))
        if entry.get("uncertain"):
            parts.append(field("Not established", e(entry["uncertain"]), "quiet"))
        if entry.get("dateNote"):
            parts.append(field("On the date", e(entry["dateNote"]), "quiet"))

        how = data["checkable"][entry["checkable"]]
        if entry.get("appendix"):
            how += (f' <a href="../evidence.html#{e(entry["appendix"])}">'
                    "See the run &rarr;</a>")
        parts.append(field("Status", f'{e(status)} — {e(data["statuses"][status])}', "quiet"))
        parts.append(field("How to check", how, "quiet"))
        if entry.get("open"):
            parts.append(field("What could change my mind", e(entry["open"]), "quiet"))

        parts.append("          </dl>\n")
        parts.append("        </div>\n")
        parts.append("      </details>\n")

    if year is not None:
        parts.append("      </div>\n")
    return "".join(parts)


def render_home(data: dict) -> str:
    """The homepage entry point. Its numbers are generated from the same data
    as the page they describe, so the homepage cannot overstate the timeline."""
    entries = data["entries"]
    dates = sorted(x["date"] for x in entries)
    turned = sum(1 for x in entries if x["status"] in TURNED)
    span = f"{short_date(dates[0])} to {short_date(dates[-1])} {dates[-1][:4]}"
    return (
        '    <section class="frame frame--short rise" id="timeline" aria-label="Timeline">\n'
        '      <p class="mark">Timeline</p>\n'
        '      <p class="years">\n'
        "        <b>How my engineering decisions changed while building real systems.</b>\n"
        f"        <span>{len(entries)} dated entries, {e(span)}. "
        f"{turned} were later revised or superseded by my own work, and those "
        "are kept as they were written.</span>\n"
        "      </p>\n"
        '      <p class="duo"><a class="lead" href="timeline/">Read the timeline</a></p>\n'
        "    </section>\n"
    )


def render_runs(data: dict) -> str:
    """The evidence appendix: one block per command that was actually executed."""
    out = ['      <section class="report">\n']
    for r in data["runs"]:
        access = {"public": "public repository",
                  "private": "private repository",
                  "local": "local repository, not published"}[r["access"]]
        out.append(f'        <div class="sec" id="{e(r["id"])}">\n')
        out.append("          <header>\n")
        out.append(f'            <p class="tag">{e(access)}</p>\n')
        out.append(f'            <h2>{e(r["claim"])}</h2>\n')
        out.append("          </header>\n")
        out.append('          <dl class="find">\n')
        out.append(field("Command", f'<code>{e(r["command"])}</code>'))
        repo = e(r["repo"])
        if r.get("url"):
            repo = f'<a href="{e(r["url"])}" rel="noreferrer">{repo}</a>'
        out.append(field("Where", f'{repo} <span class="quiet">@ {e(r["sha"][:12])}</span>'))
        out.append(field("When", e(r["when"]), "quiet"))
        out.append(field("Printed", f'<code>{e(r["expect"])}</code>'))
        out.append(field("Full output", f'<a href="{e(r["file"])}">{e(r["file"])}</a>'))
        if r.get("note"):
            out.append(field("Note", e(r["note"]), "quiet"))
        out.append("          </dl>\n")
        out.append("        </div>\n")
    out.append("      </section>\n")
    return "".join(out)


def splice(page: str, start: str, end: str, body: str, indent: str, name: str):
    if start not in page or end not in page:
        print(f"{name} is missing its markers", file=sys.stderr)
        return None
    head, rest = page.split(start, 1)
    _, tail = rest.split(end, 1)
    return head + f"{start}\n{body}{indent}{end}" + tail


def main() -> int:
    check = "--check" in sys.argv
    data = json.loads(DATA.read_text(encoding="utf-8"))
    runs = json.loads(RUNS.read_text(encoding="utf-8"))

    files = [
        (PAGE, START, END, render(data), "    ", "timeline/index.html"),
        (HOME, HOME_START, HOME_END, render_home(data), "    ", "index.html"),
        (RUNS_PAGE, RUNS_START, RUNS_END, render_runs(runs), "    ", "evidence.html"),
    ]

    written = []
    for path, start, end, body, indent, name in files:
        current = path.read_text(encoding="utf-8")
        updated = splice(current, start, end, body, indent, name)
        if updated is None:
            return 1
        written.append((path, current, updated, name))

    # A number on the page must still be in the output it came from. This is
    # the check that stops the appendix drifting away from the run behind it.
    missing = []
    for r in runs["runs"]:
        f = ROOT / r["file"]
        if not f.exists():
            missing.append(f"{r['id']}: {r['file']} is missing")
        elif r["expect"] not in f.read_text(encoding="utf-8", errors="replace"):
            missing.append(f"{r['id']}: {r['expect']!r} is not in {r['file']}")
    if missing:
        print("EVIDENCE DRIFT\n", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        return 1

    if check:
        bad = [name for _, current, updated, name in written if current != updated]
        if bad:
            print("RENDER DRIFT\n", file=sys.stderr)
            for b in bad:
                print(f"  {b} does not match its data", file=sys.stderr)
            print("\n  Run: python3 tool/render-timeline.py", file=sys.stderr)
            return 1
        print(f"TIMELINE OK — {len(data['entries'])} entries and "
              f"{len(runs['runs'])} recorded runs match their data, the "
              "homepage counts match the timeline, and every expected line is "
              "present in its captured output")
        return 0

    for path, _, updated, _ in written:
        path.write_text(updated, encoding="utf-8")
    print(f"rendered {len(data['entries'])} entries into timeline/index.html, "
          f"the entry point into index.html and {len(runs['runs'])} runs into "
          "evidence.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
