/**
 * Renders one 1200x630 social card per route into public/og/.
 *
 * Why the cards are committed rather than generated by a Next route handler:
 * `opengraph-image.tsx` emits `out/opengraph-image` with no file extension, and
 * GitHub Pages serves an extensionless file as application/octet-stream, which
 * preview crawlers reject. Real .png files under /og/ get the right MIME type.
 *
 * Text comes from src/lib/seo.ts — the same rows the pages build their <head>
 * from — so a card cannot say something the page does not.
 *
 * Run:  npm run og
 * Node must support --experimental-strip-types (22.6+); see package.json.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import React from "react"
import { ImageResponse } from "next/og.js"
import { ROUTES, SITE } from "../src/lib/seo.ts"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..")
const outDir = join(root, "public", "og")

const C = {
  bg: "#F8F8F6",
  fg: "#111111",
  body: "#3A3A38",
  line: "#E3E3DF",
  dim: "#AAAAAA",
}

const font = (f) => readFile(join(here, "fonts", f))

const [serif, sans, mono] = await Promise.all([
  font("InstrumentSerif-Regular.ttf"),
  font("Inter-Regular.ttf"),
  font("JetBrainsMono-Medium.ttf"),
])

const fonts = [
  { name: "Instrument Serif", data: serif, weight: 400, style: "normal" },
  { name: "Inter", data: sans, weight: 400, style: "normal" },
  { name: "JetBrains Mono", data: mono, weight: 500, style: "normal" },
]

const h = React.createElement

/** Serif display size steps down as the line gets longer, so it never wraps past two lines. */
function titleSize(text) {
  if (text.length <= 18) return 92
  if (text.length <= 32) return 76
  if (text.length <= 48) return 62
  return 52
}

function card(route) {
  const title = route.ogTitle ?? route.title

  return h(
    "div",
    {
      style: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        height: "100%",
        background: C.bg,
        color: C.fg,
        fontFamily: "Inter",
        padding: 64,
      },
    },
    // Thin inset frame, the same hairline the site uses around every card.
    h(
      "div",
      {
        style: {
          display: "flex",
          flexDirection: "column",
          flex: 1,
          border: `1px solid ${C.line}`,
          background: "#FFFFFF",
          padding: "56px 60px",
          justifyContent: "space-between",
        },
      },
      h(
        "div",
        { style: { display: "flex", flexDirection: "column" } },
        h(
          "div",
          {
            style: {
              display: "flex",
              fontFamily: "JetBrains Mono",
              fontSize: 20,
              letterSpacing: 3,
              textTransform: "uppercase",
              color: C.dim,
              marginBottom: 28,
            },
          },
          route.ogLabel,
        ),
        h(
          "div",
          {
            style: {
              display: "flex",
              fontFamily: "Instrument Serif",
              fontSize: titleSize(title),
              lineHeight: 1.08,
              color: C.fg,
              maxWidth: 940,
            },
          },
          title,
        ),
        h(
          "div",
          {
            style: {
              display: "flex",
              fontSize: 23,
              lineHeight: 1.5,
              color: C.body,
              marginTop: 28,
              maxWidth: 900,
            },
          },
          // Two lines at most; the full description stays in the meta tag.
          truncate(route.description, 155),
        ),
      ),
      h(
        "div",
        {
          style: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            borderTop: `1px solid ${C.line}`,
            paddingTop: 26,
            fontFamily: "JetBrains Mono",
            fontSize: 19,
            color: C.dim,
          },
        },
        h("div", { style: { display: "flex" } }, "huypkc.github.io"),
        h(
          "div",
          { style: { display: "flex", color: C.body } },
          `${SITE.name} · ${SITE.jobTitle}`,
        ),
      ),
    ),
  )
}

function truncate(text, max) {
  if (text.length <= max) return text
  const cut = text.slice(0, max)
  return `${cut.slice(0, cut.lastIndexOf(" "))}…`
}

/** Monogram favicon: the site's own serif, inverted so it reads at 16px. */
function icon(size) {
  return h(
    "div",
    {
      style: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        background: C.fg,
        color: "#FFFFFF",
        fontFamily: "Instrument Serif",
        fontSize: Math.round(size * 0.56),
        letterSpacing: Math.round(size * -0.01),
        // Optical centring: the serif sits slightly high in its em box.
        paddingBottom: Math.round(size * 0.06),
      },
    },
    "HT",
  )
}

await mkdir(outDir, { recursive: true })
await mkdir(join(root, "public", "icons"), { recursive: true })

for (const [name, size] of [
  ["icon-512", 512],
  ["icon-192", 192],
  ["apple-icon", 180],
  ["icon-32", 32],
]) {
  const res = new ImageResponse(icon(size), { width: size, height: size, fonts })
  const buf = Buffer.from(await res.arrayBuffer())
  await writeFile(join(root, "public", "icons", `${name}.png`), buf)
  console.log(`icons/${name}.png  ${String(Math.round(buf.length / 1024)).padStart(4)} KB`)
}

for (const route of ROUTES) {
  const res = new ImageResponse(card(route), { width: 1200, height: 630, fonts })
  const buf = Buffer.from(await res.arrayBuffer())
  const file = join(outDir, `${route.card}.png`)
  await writeFile(file, buf)
  console.log(
    `${route.card}.png  ${String(Math.round(buf.length / 1024)).padStart(4)} KB  ${route.path}`,
  )
}

console.log(`\n${ROUTES.length} cards written to public/og/`)
