#!/usr/bin/env python3
"""Render the Engineering Log from data into index.html.

Why a generator rather than fetching JSON in the browser: this site has no
build step and has to stay useful with JavaScript off. Rendering client-side
would put the whole log behind JS, which is exactly the failure the page is
written against. Rendering at author time keeps one structured source of
truth (data/engineering-log.json) and ships plain static HTML that works with
no script at all. Expand and collapse is native <details>, so that works with
no script either.

The generated block lives between two markers in index.html and is committed,
so the file on disk is the file that is served. --check re-renders and
compares, which is what stops the data and the page drifting apart.

Standard library only, so CI needs no install step.

    python3 tool/render-log.py           # write
    python3 tool/render-log.py --check   # verify committed HTML matches data
"""

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "engineering-log.json"
PAGE = ROOT / "index.html"
RUNS = ROOT / "data" / "runs.json"
RUNS_PAGE = ROOT / "evidence.html"

START = "<!-- engineering-log:start · generated by tool/render-log.py · edit data/engineering-log.json -->"
END = "<!-- engineering-log:end -->"
RUNS_START = "<!-- runs:start · generated by tool/render-log.py · edit data/runs.json -->"
RUNS_END = "<!-- runs:end -->"

# The status vocabulary maps onto pill classes the stylesheet already carries,
# so the log borrows the report's visual language instead of inventing one.
PILL = {
    "VERIFIED": "pill--verified",
    "SUPPORTED": "pill--tested",
    "INFERRED": "pill--na",
    "SUPERSEDED": "pill--no",
}

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def e(text: str) -> str:
    return html.escape(str(text), quote=True)


def slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:60]


def short_date(iso: str) -> str:
    y, m, d = iso.split("-")
    return f"{MONTHS[int(m) - 1]} {int(d)}"


def field(label: str, value: str, cls: str = "") -> str:
    c = f' class="{cls}"' if cls else ""
    return (f"        <div><dt>{e(label)}</dt>"
            f"<dd{c}>{value}</dd></div>\n")


def evidence_list(items: list) -> str:
    out = []
    for it in items:
        label = e(it["label"])
        url = it.get("url")
        if url:
            body = f'<a href="{e(url)}" rel="noreferrer">{label}</a>'
        else:
            body = label
        repo = it.get("repo")
        access = it.get("access")
        if repo:
            tail = e(repo)
            if access == "private":
                tail += " · private repository, reference not a link"
            elif access == "local":
                tail += " · local repository, not published"
            body += f' <span class="quiet">{tail}</span>'
        out.append(f"<li>{body}</li>")
    return '<ul class="ev">' + "".join(out) + "</ul>"


def render(data: dict) -> str:
    entries = sorted(data["entries"], key=lambda x: x["date"], reverse=True)
    parts = [
        '      <section class="frame frame--short rise" id="log" aria-label="Engineering log">\n',
        '        <p class="mark">Engineering log</p>\n',
        '        <p class="logsay">What was observed, what was decided because of it, '
        'and what the claim rests on. Each line opens.</p>\n',
    ]
    year = None
    for entry in entries:
        y = entry["date"][:4]
        if y != year:
            if year is not None:
                parts.append("        </div>\n")
            year = y
            parts.append(f'        <p class="logyear">{e(y)}</p>\n')
            parts.append('        <div class="log">\n')

        status = entry["status"]
        pill = PILL.get(status, "pill--na")
        eid = f'log-{entry["date"]}-{slug(entry["title"])}'

        parts.append(f'        <details class="entry" id="{e(eid)}">\n')
        parts.append('          <summary>\n')
        parts.append(f'            <span class="when">{e(short_date(entry["date"]))}</span>\n')
        parts.append(f'            <span class="what">{e(entry["title"])}</span>\n')
        parts.append(f'            <span class="pill {pill}">{e(status)}</span>\n')
        parts.append('          </summary>\n')
        parts.append('          <div class="entrybody">\n')
        parts.append(f'            <p class="entrymeta">{e(entry["project"])} · {e(entry["type"])}</p>\n')
        parts.append('            <dl class="find">\n')

        rows = [
            ("Observation", entry.get("observation")),
            ("Context", entry.get("trigger")),
            ("Measured", entry.get("measurement")),
            ("Judgment", entry.get("hypothesis")),
            ("Consequence", entry.get("consequence")),
            ("Correction", entry.get("correction")),
            ("Boundary", entry.get("boundary")),
        ]
        for label, value in rows:
            if value:
                parts.append(field(label, e(value)))
        parts.append(field("Evidence", evidence_list(entry["evidence"])))
        parts.append(field("Status", e(status), "quiet"))
        how = data["checkable"][entry["checkable"]]
        if entry.get("appendix"):
            how += (f' <a href="evidence.html#{e(entry["appendix"])}">'
                    "See the run &rarr;</a>")
        parts.append(field("How to check", how, "quiet"))
        parts.append(field("Falsified by", e(entry["falsifier"]), "quiet"))
        if entry.get("supersededBy"):
            parts.append(field("Superseded by", e(entry["supersededBy"])))
        parts.append("            </dl>\n")
        parts.append("          </div>\n")
        parts.append("        </details>\n")

    if year is not None:
        parts.append("        </div>\n")
    parts.append('        <p class="duo"><a href="evidence.html">'
                 "The commands behind the numbers</a></p>\n")
    parts.append("      </section>\n")
    return "".join(parts)


def render_runs(data: dict) -> str:
    """The evidence appendix: one block per command that was actually executed."""
    out = ['      <section class="report">\n']
    for r in data["runs"]:
        access = {"public": "public repository",
                  "private": "private repository",
                  "local": "local repository, not published"}[r["access"]]
        out.append(f'        <div class="sec" id="{e(r["id"])}">\n')
        out.append('          <header>\n')
        out.append(f'            <p class="tag">{e(access)}</p>\n')
        out.append(f'            <h2>{e(r["claim"])}</h2>\n')
        out.append('          </header>\n')
        out.append('          <dl class="find">\n')
        out.append(field("Command", f'<code>{e(r["command"])}</code>'))
        repo = e(r["repo"])
        if r.get("url"):
            repo = f'<a href="{e(r["url"])}" rel="noreferrer">{repo}</a>'
        out.append(field("Where", f'{repo} <span class="quiet">@ {e(r["sha"][:12])}</span>'))
        out.append(field("When", e(r["when"]), "quiet"))
        out.append(field("Printed", f'<code>{e(r["expect"])}</code>'))
        out.append(field("Full output",
                         f'<a href="{e(r["file"])}">{e(r["file"])}</a>'))
        if r.get("note"):
            out.append(field("Note", e(r["note"]), "quiet"))
        out.append("          </dl>\n")
        out.append("        </div>\n")
    out.append("      </section>\n")
    return "".join(out)


def splice(page: str, start: str, end: str, body: str, name: str):
    if start not in page or end not in page:
        print(f"{name} is missing its markers", file=sys.stderr)
        return None
    head, rest = page.split(start, 1)
    _, tail = rest.split(end, 1)
    return head + f"{start}\n{body}    {end}" + tail


def main() -> int:
    check = "--check" in sys.argv
    data = json.loads(DATA.read_text(encoding="utf-8"))
    runs = json.loads(RUNS.read_text(encoding="utf-8"))
    page = PAGE.read_text(encoding="utf-8")
    runs_page = RUNS_PAGE.read_text(encoding="utf-8")

    updated = splice(page, START, END, render(data), "index.html")
    updated_runs = splice(runs_page, RUNS_START, RUNS_END,
                          render_runs(runs), "evidence.html")
    if updated is None or updated_runs is None:
        return 1

    # A number on the page must still be in the output it came from. This is the
    # check that stops the appendix drifting away from the run behind it.
    missing = []
    for r in runs["runs"]:
        f = ROOT / r["file"]
        if not f.exists():
            missing.append(f"{r['id']}: {r['file']} is missing")
        elif r["expect"] not in f.read_text(encoding="utf-8", errors="replace"):
            missing.append(f"{r['id']}: {r['expect']!r} is not in {r['file']}")
    if missing:
        print("EVIDENCE DRIFT\n", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        return 1

    if check:
        bad = []
        if updated != page:
            bad.append("index.html does not match data/engineering-log.json")
        if updated_runs != runs_page:
            bad.append("evidence.html does not match data/runs.json")
        if bad:
            print("RENDER DRIFT\n", file=sys.stderr)
            for b in bad:
                print(f"  {b}", file=sys.stderr)
            print("\n  Run: python3 tool/render-log.py", file=sys.stderr)
            return 1
        print(f"LOG OK — {len(data['entries'])} entries and {len(runs['runs'])} "
              "recorded runs match their data, and every expected line is "
              "present in its captured output")
        return 0

    PAGE.write_text(updated, encoding="utf-8")
    RUNS_PAGE.write_text(updated_runs, encoding="utf-8")
    print(f"rendered {len(data['entries'])} entries into index.html and "
          f"{len(runs['runs'])} runs into evidence.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
